name: CI - Tests

on:
  pull_request:
    branches: main
  push:
    branches: main
    
jobs:
  api_test:
    name: API Test
    runs-on: ubuntu-latest
    steps:    
      - name: Cloning repository to GitGub Actions VM runner
        uses: actions/checkout@v4
        
      - name: Start the containers
        run: make build-up
        
      - name: Test the Laravel API
        run: make api-test
      
    
      
      
    
